In [1]:
#Load required packages
library(tidyverse)
library(geosphere)

Warning message:
“package ‘tidyr’ was built under R version 4.4.3”
Warning message:
“package ‘readr’ was built under R version 4.4.3”
Warning message:
“package ‘dplyr’ was built under R version 4.4.3”
Warning message:
“package ‘stringr’ was built under R version 4.4.3”
Warning message:
“package ‘forcats’ was built under R version 4.4.3”
Warning message:
“package ‘lubridate’ was built under R version 4.4.3”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   4.0.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
#Get list of BAMfiles and check length
bamlist<-read.table('/home/jbos/Moz_reads/bam_names_grp137.txt')
nrow(bamlist)

[1] 236

In [3]:
#Little function to get sample names from BAM filepaths
bamnames<-function(bam){
    a<-strsplit(bam,'files/')[[1]][2]
    b<-strsplit(a,'.s')[[1]][1]
    return(b)
    }

In [4]:
indlist<-apply(bamlist,FUN=bamnames,MARGIN=1)

In [6]:
#Read in NGSrelate output
rels<-read.table('/scratch/jbos/Moz_aligned_mil/glf_grp137/newres',header=TRUE)
colnames(rels)
nrow(rels)

 [1] "a"                      "b"                      "nSites"
 [4] "J9"                     "J8"                     "J7"
 [7] "J6"                     "J5"                     "J4"
[10] "J3"                     "J2"                     "J1"
[13] "rab"                    "Fa"                     "Fb"
[16] "theta"                  "inbred_relatedness_1_2" "inbred_relatedness_2_1"
[19] "fraternity"             "identity"               "zygosity"
[22] "X2of3_IDB"              "FDiff"                  "loglh"
[25] "nIter"                  "bestoptimll"            "coverage"
[28] "X2dsfs"                 "R0"                     "R1"
[31] "KING"                   "X2dsfs_loglike"         "X2dsfsf_niter"

[1] 27730

In [7]:
#Do some shenanigans to properly name all individuals in each relative pair
indlist_a<-as.data.frame(indlist)
indlist_a$a<-c(seq(0,235,1))
colnames(indlist_a)<-c('IndA','a')

In [8]:
relsa<-left_join(rels,indlist_a)

Joining with `by = join_by(a)`

In [9]:
indlist_b<-as.data.frame(indlist)
indlist_b$b<-c(seq(0,235,1))
colnames(indlist_b)<-c('IndB','b')

In [10]:
rels_all<-left_join(relsa,indlist_b)

Joining with `by = join_by(b)`

In [12]:
#Check median KING relatedness
median(rels_all$KING)

[1] 0.1283985

In [13]:
#Get list of DB individuals
grp1<-read.table('/home/jbos/Moz_reads/bam_names_grp1.txt')
grp1<-sapply(strsplit(grp1$V1, "files/"), "[", 2)
grp1<-sapply(strsplit(grp1, ".sor"), "[", 1)

In [14]:
#Sort out DB individuals
rels_all$BayA<-0
rels_all$BayA[rels_all$IndA %in% grp1]<-1

rels_all$BayB<-0
rels_all$BayB[rels_all$IndB %in% grp1]<-1

In [18]:
table(rels_all$BayA)

    0     1
13203 14527

In [16]:
DB<-rels_all[rels_all$BayA==1,]
DB<-DB[DB$BayB==1,]

In [17]:
#Check median relatedness of DB vs all, just for fun
median(rels_all$KING)
median(DB$KING)

[1] 0.1283985

[1] 0.160522

In [18]:
#This output has too many columns
which(colnames(rels_all)=='KING')

[1] 31

In [19]:
#Look at all KING coefficients in order
rels_all[order(-rels_all$KING),31]

    [1]  0.440890  0.435617  0.238824  0.238658  0.227789  0.226161  0.221046
    [8]  0.216856  0.212239  0.211282  0.209890  0.208177  0.207401  0.203856
   [15]  0.198747  0.194990  0.193659  0.192583  0.192014  0.191867  0.191629
   [22]  0.191571  0.191509  0.190703  0.190577  0.190056  0.189347  0.189222
   [29]  0.189065  0.188384  0.188358  0.188277  0.188028  0.187894  0.187630
   [36]  0.187588  0.187027  0.186651  0.186596  0.186489  0.186426  0.186391
   [43]  0.186246  0.186229  0.186153  0.186051  0.186026  0.186016  0.185933
   [50]  0.185873  0.185861  0.185776  0.185742  0.185666  0.185542  0.185501
   [57]  0.185320  0.185129  0.185115  0.184844  0.184790  0.184739  0.184708
   [64]  0.184473  0.184380  0.184090  0.183928  0.183895  0.183867  0.183821
   [71]  0.183771  0.183741  0.183551  0.183523  0.183514  0.183379  0.183277
   [78]  0.183260  0.183217  0.183088  0.182975  0.182972  0.182908  0.182838
   [85]  0.182788  0.182768  0.182743  0.182684  0.182619  0.182389  0.182322
   [92]  0.182138  0.182133  0.182046  0.182043  0.182013  0.181963  0.181761
   [99]  0.181741  0.181620  0.181549  0.181548  0.181517  0.181509  0.181488
  [106]  0.181268  0.181222  0.181171  0.181149  0.181130  0.181024  0.180995
  [113]  0.180966  0.180943  0.180883  0.180866  0.180811  0.180663  0.180657
  [120]  0.180556  0.180554  0.180540  0.180427  0.180427  0.180424  0.180307
  [127]  0.180275  0.180269  0.180249  0.180226  0.180195  0.180190  0.180177
  [134]  0.180134  0.180027  0.180018  0.179998  0.179931  0.179915  0.179735
  [141]  0.179619  0.179616  0.179603  0.179576  0.179531  0.179408  0.179384
  [148]  0.179374  0.179365  0.179304  0.179249  0.179245  0.179222  0.179201
  [155]  0.179025  0.178968  0.178965  0.178927  0.178803  0.178702  0.178688
  [162]  0.178669  0.178637  0.178637  0.178477  0.178456  0.178331  0.178307
  [169]  0.178266  0.178150  0.178069  0.177858  0.177837  0.177823  0.177771
  [176]  0.177707  0.177608  0.177603  0.177601  0.177600  0.177557  0.177546
  [183]  0.177505  0.177485  0.177483  0.177352  0.177333  0.177294  0.177252
  [190]  0.177089  0.177036  0.177014  0.177003  0.176956  0.176856  0.176850
  [197]  0.176809  0.176808  0.176781  0.176752  0.176636  0.176592  0.176591
  [204]  0.176588  0.176557  0.176546  0.176492  0.176421  0.176373  0.176353
  [211]  0.176322  0.176203  0.176143  0.176139  0.176115  0.176056  0.176005
  [218]  0.176005  0.175942  0.175914  0.175888  0.175840  0.175777  0.175776
  [225]  0.175753  0.175682  0.175653  0.175620  0.175554  0.175552  0.175543
  [232]  0.175502  0.175478  0.175462  0.175428  0.175363  0.175358  0.175353
  [239]  0.175278  0.175246  0.175213  0.175212  0.175095  0.174977  0.174962
  [246]  0.174945  0.174860  0.174783  0.174755  0.174726  0.174527  0.174443
  [253]  0.174424  0.174405  0.174294  0.174282  0.174243  0.174241  0.174228
  [260]  0.174225  0.174216  0.174209  0.174206  0.174204  0.174147  0.174124
  [267]  0.174112  0.174095  0.174042  0.174032  0.174003  0.173972  0.173971
  [274]  0.173941  0.173932  0.173923  0.173904  0.173895  0.173883  0.173883
  [281]  0.173824  0.173823  0.173804  0.173795  0.173763  0.173706  0.173699
  [288]  0.173684  0.173668  0.173654  0.173617  0.173532  0.173521  0.173494
  [295]  0.173463  0.173459  0.173454  0.173417  0.173408  0.173403  0.173374
  [302]  0.173369  0.173355  0.173354  0.173331  0.173310  0.173303  0.173283
  [309]  0.173242  0.173241  0.173202  0.173179  0.173177  0.173135  0.173131
  [316]  0.173126  0.173104  0.173053  0.173053  0.173049  0.173004  0.173003
  [323]  0.172992  0.172975  0.172911  0.172898  0.172870  0.172861  0.172852
  [330]  0.172834  0.172829  0.172817  0.172814  0.172809  0.172796  0.172770
  [337]  0.172769  0.172761  0.172737  0.172716  0.172704  0.172684  0.172672
  [344]  0.172667  0.172652  0.172632  0.172622  0.172612  0.172580  0.172575
  [351]  0.172568  0.172559  0.172538  0.172526  0.172510  0.172491  0.172489
  [358]  0.172486  0.172474  0.172471  0.172460  0.172411  0.172405  0.172359
  [365]  0.172322  0.172316  0.172307  0.172280  0.172252  0.172238  0.172227
  [372]  0.172222  0.172220  0.172220  0.172200  0.172181  0.172181  0.172173
  [379]  0.172168  0.172132  0.172106  0.172098  0.172077  0.172075  0.172058
  [386]  0.172039  0.172037  0.172030  0.172018  0.172006  0.171973  0.171968
  [393]  0.171959  0.171945  0.171927  0.171903  0.171901  0.171881  0.171866
  [400]  0.171855  0.171847  0.171835  0.171797  0.171778  0.171753  0.171751
  [407]  0.171747  0.171736  0.171729  0.171720  0.171715  0.171695  0.171614
  [414]  0.171605  0.171594  0.171585  0.171584  0.171579  0.171566  0.171565
  [421]  0.171555  0.171544  0.171537  0.171530  0.171515  0.171510  0.171483
  [428]  0.171478  0.171469  0.171468  0.171456  0.171446  0.171431  0.171416
  [435]  0.171414  0.171411  0.171407  0.171398  0.171383  0.171372  0.171353
  [442]  0.171336  0.171327  0.171308  0.171308  0.171302  0.171293  0.171285
  [449]  0.171265  0.171264  0.171263  0.171244  0.171234  0.171231  0.171225
  [456]  0.171207  0.171199  0.171188  0.171166  0.171157  0.171154  0.171129
  [463]  0.171127  0.171124  0.171012  0.170985  0.170981  0.170966  0.170949
  [470]  0.170943  0.170908  0.170882  0.170864  0.170794  0.170777  0.170772
  [477]  0.170762  0.170756  0.170740  0.170738  0.170733  0.170729  0.170702
  [484]  0.170700  0.170686  0.170684  0.170674  0.170666  0.170650  0.170638
  [491]  0.170631  0.170622  0.170610  0.170607  0.170600  0.170598  0.170595
  [498]  0.170579  0.170572  0.170563  0.170542  0.170528  0.170504  0.170477
  [505]  0.170474  0.170471  0.170451  0.170448  0.170446  0.170445  0.170412
  [512]  0.170356  0.170349  0.170337  0.170327  0.170326  0.170322  0.170303
  [519]  0.170277  0.170275  0.170270  0.170265  0.170263  0.170244  0.170223
  [526]  0.170210  0.170195  0.170184  0.170167  0.170156  0.170116  0.170106
  [533]  0.170103  0.170099  0.170090  0.170075  0.170068  0.170068  0.170066
  [540]  0.170039  0.170036  0.170027  0.170020  0.170019  0.169990  0.169963
  [547]  0.169944  0.169927  0.169919  0.169916  0.169888  0.169881  0.169870
  [554]  0.169832  0.169815  0.169799  0.169788  0.169787  0.169784  0.169763
  [561]  0.169747  0.169737  0.169711  0.169699  0.169694  0.169693  0.169667
  [568]  0.169654  0.169653  0.169638  0.169620  0.169607  0.169548  0.169513
  [575]  0.169506  0.169501  0.169460  0.169456  0.169449  0.169446  0.169444
  [582]  0.169441  0.169439  0.169416  0.169406  0.169382  0.169373  0.169372
  [589]  0.169369  0.169368  0.169355  0.169334  0.169331  0.169295  0.169293
  [596]  0.169278  0.169269  0.169260  0.169239  0.169234  0.169226  0.169215
  [603]  0.169209  0.169189  0.169183  0.169180  0.169169  0.169164  0.169161
  [610]  0.169159  0.169084  0.169068  0.169052  0.169049  0.169047  0.169029
  [617]  0.168969  0.168969  0.168969  0.168949  0.168938  0.168937  0.168936
  [624]  0.168934  0.168914  0.168911  0.168902  0.168893  0.168886  0.168856
  [631]  0.168843  0.168840  0.168834  0.168834  0.168819  0.168810  0.168799
  [638]  0.168784  0.168751  0.168737  0.168731  0.168703  0.168666  0.168666
  [645]  0.168663  0.168663  0.168652  0.168652  0.168651  0.168651  0.168639
  [652]  0.168632  0.168632  0.168628  0.168620  0.168617  0.168616  0.168611
  [659]  0.168609  0.168604  0.168590  0.168525  0.168517  0.168514  0.168506
  [666]  0.168504  0.168488  0.168475  0.168460  0.168455  0.168447  0.168439
  [673]  0.168429  0.168425  0.168421  0.168419  0.168404  0.168379  0.168364
  [680]  0.168345  0.168330  0.168321  0.168287  0.168248  0.168241  0.168227
  [687]  0.168216  0.168212  0.168211  0.168211  0.168194  0.168185  0.168172
  [694]  0.168143  0.168127  0.168120  0.168098  0.168096  0.168086  0.168085
  [701]  0.168084  0.168082  0.168074  0.168065  0.168056  0.168053  0.168040
  [708]  0.168033  0.168033  0.168025  0.168015  0.167999  0.167989  0.167976
  [715]  0.167974  0.167973  0.167972  0.167972  0.167962  0.167958  0.167943
  [722]  0.167939  0.167923  0.167904  0.167904  0.167863  0.167863  0.167836
  [729]  0.167836  0.167834  0.167815  0.167812  0.167808  0.167798  0.167795
  [736]  0.167788  0.167788  0.167777  0.167770  0.167770  0.167765  0.167764
  [743]  0.167754  0.167753  0.167749  0.167725  0.167713  0.167697  0.167695
  [750]  0.167691  0.167682  0.167673  0.167673  0.167665  0.167659  0.167654
  [757]  0.167652  0.167649  0.167645  0.167638  0.167596  0.167596  0.167591
  [764]  0.167590  0.167580  0.167579  0.167573  0.167572  0.167555  0.167548
  [771]  0.167517  0.167511  0.167511  0.167506  0.167502  0.167491  0.167484
  [778]  0.167480  0.167462  0.167442  0.167427  0.167414  0.167398  0.167394
  [785]  0.167394  0.167390  0.167376  0.167366  0.167348  0.167337  0.167329
  [792]  0.167323  0.167318  0.167316  0.167313  0.167301  0.167283  0.167282
  [799]  0.167274  0.167270  0.167268  0.167234  0.167233  0.167211  0.167209
  [806]  0.167206  0.167199  0.167198  0.167191  0.167190  0.167189  0.167182
  [813]  0.167169  0.167166  0.167160  0.167154  0.167140  0.167136  0.167105
  [820]  0.167103  0.167102  0.167094  0.167079  0.167078  0.167073  0.167068
  [827]  0.167053  0.167052  0.167050  0.167049  0.167047  0.167041  0.167038
  [834]  0.167035  0.167029  0.167024  0.167014  0.166997  0.166993  0.166989
  [841]  0.166969  0.166959  0.166959  0.166954  0.166941  0.166916  0.166909
  [848]  0.166899  0.166898  0.166895  0.166894  0.166870  0.166864  0.166861
  [855]  0.166842  0.166822  0.166816  0.166810  0.166809  0.166808  0.166801
  [862]  0.166800  0.166788  0.166785  0.166779  0.166767  0.166763  0.166759
  [869]  0.166758  0.166754  0.166742  0.166740  0.166724  0.166713  0.166711
  [876]  0.166711  0.166709  0.166696  0.166695  0.166651  0.166650  0.166640
  [883]  0.166613  0.166603  0.166602  0.166601  0.166597  0.166594  0.166554
  [890]  0.166553  0.166539  0.166532  0.166528  0.166518  0.166515  0.166501
  [897]  0.166497  0.166495  0.166491  0.166489  0.166488  0.166478  0.166478
  [904]  0.166471  0.166466  0.166444  0.166438  0.166425  0.166415  0.166402
  [911]  0.166400  0.166393  0.166371  0.166367  0.166350  0.166319  0.166318
  [918]  0.166306  0.166304  0.166303  0.166296  0.166290  0.166286  0.166280
  [925]  0.166278  0.166266  0.166263  0.166255  0.166246  0.166241  0.166240
  [932]  0.166227  0.166192  0.166181  0.166172  0.166164  0.166163  0.166159
  [939]  0.166134  0.166123  0.166105  0.166103  0.166100  0.166098  0.166091
  [946]  0.166084  0.166083  0.166079  0.166070  0.166070  0.166068  0.166067
  [953]  0.166054  0.166042  0.166019  0.166015  0.166014  0.165996  0.165989
  [960]  0.165978  0.165969  0.165953  0.165940  0.165930  0.165930  0.165920
  [967]  0.165919  0.165916  0.165913  0.165912  0.165908  0.165904  0.165883
  [974]  0.165874  0.165870  0.165862  0.165855  0.165855  0.165846  0.165835
  [981]  0.165834  0.165805  0.165784  0.165775  0.165767  0.165764  0.165762
  [988]  0.165761  0.165759  0.165743  0.165740  0.165736  0.165736  0.165731
  [995]  0.165729  0.165728  0.165722  0.165698  0.165669  0.165667  0.165667
 [1002]  0.165658  0.165657  0.165654  0.165654  0.165643  0.165640  0.165638
 [1009]  0.165631  0.165630  0.165622  0.165622  0.165618  0.165613  0.165607
 [1016]  0.165597  0.165580  0.165579  0.165576  0.165572  0.165561  0.165554
 [1023]  0.165550  0.165533  0.165519  0.165518  0.165514  0.165513  0.165503
 [1030]  0.165498  0.165493  0.165492  0.165459  0.165458  0.165457  0.165453
 [1037]  0.165451  0.165439  0.165428  0.165422  0.165415  0.165413  0.165409
 [1044]  0.165393  0.165392  0.165391  0.165390  0.165389  0.165379  0.165362
 [1051]  0.165361  0.165343  0.165340  0.165337  0.165335  0.165326  0.165324
 [1058]  0.165306  0.165277  0.165264  0.165256  0.165248  0.165246  0.165243
 [1065]  0.165243  0.165237  0.165233  0.165221  0.165220  0.165220  0.165219
 [1072]  0.165213  0.165209  0.165205  0.165201  0.165178  0.165150  0.165149
 [1079]  0.165147  0.165146  0.165143  0.165137  0.165132  0.165132  0.165124
 [1086]  0.165104  0.165079  0.165078  0.165073  0.165063  0.165051  0.165044
 [1093]  0.165038  0.165036  0.165033  0.165029  0.165019  0.165018  0.165017
 [1100]  0.165013  0.165009  0.164989  0.164968  0.164964  0.164960  0.164946
 [1107]  0.164945  0.164931  0.164930  0.164925  0.164918  0.164913  0.164908
 [1114]  0.164893  0.164854  0.164850  0.164850  0.164833  0.164832  0.164825
 [1121]  0.164803  0.164801  0.164799  0.164792  0.164790  0.164779  0.164774
 [1128]  0.164773  0.164771  0.164768  0.164766  0.164761  0.164761  0.164755
 [1135]  0.164745  0.164741  0.164740  0.164733  0.164715  0.164710  0.164698
 [1142]  0.164696  0.164679  0.164670  0.164667  0.164648  0.164638  0.164614
 [1149]  0.164613  0.164610  0.164604  0.164602  0.164597  0.164596  0.164593
 [1156]  0.164591  0.164586  0.164582  0.164576  0.164572  0.164556  0.164551
 [1163]  0.164550  0.164550  0.164546  0.164546  0.164537  0.164533  0.164526
 [1170]  0.164517  0.164500  0.164487  0.164479  0.164465  0.164459  0.164438
 [1177]  0.164436  0.164434  0.164430  0.164423  0.164423  0.164423  0.164413
 [1184]  0.164413  0.164402  0.164399  0.164396  0.164396  0.164390  0.164390
 [1191]  0.164389  0.164349  0.164348  0.164344  0.164339  0.164337  0.164330
 [1198]  0.164330  0.164328  0.164325  0.164321  0.164311  0.164306  0.164291
 [1205]  0.164290  0.164265  0.164263  0.164252  0.164241  0.164239  0.164235
 [1212]  0.164234  0.164234  0.164223  0.164218  0.164213  0.164208  0.164197
 [1219]  0.164187  0.164187  0.164184  0.164182  0.164171  0.164167  0.164159
 [1226]  0.164149  0.164131  0.164120  0.164120  0.164116  0.164114  0.164108
 [1233]  0.164098  0.164098  0.164096  0.164094  0.164088  0.164087  0.164086
 [1240]  0.164082  0.164080  0.164070  0.164069  0.164066  0.164065  0.164063
 [1247]  0.164057  0.164053  0.164046  0.164042  0.164038  0.164018  0.164004
 [1254]  0.163998  0.163993  0.163984  0.163984  0.163956  0.163946  0.163946
 [1261]  0.163946  0.163944  0.163942  0.163935  0.163933  0.163931  0.163904
 [1268]  0.163902  0.163900  0.163885  0.163879  0.163871  0.163859  0.163857
 [1275]  0.163840  0.163837  0.163836  0.163830  0.163824  0.163787  0.163786
 [1282]  0.163783  0.163775  0.163774  0.163773  0.163741  0.163733  0.163731
 [1289]  0.163730  0.163724  0.163724  0.163716  0.163697  0.163690  0.163685
 [1296]  0.163683  0.163680  0.163656  0.163656  0.163628  0.163604  0.163567
 [1303]  0.163563  0.163546  0.163543  0.163543  0.163539  0.163537  0.163534
 [1310]  0.163529  0.163527  0.163526  0.163521  0.163517  0.163516  0.163511
 [1317]  0.163499  0.163494  0.163488  0.163475  0.163469  0.163453  0.163444
 [1324]  0.163441  0.163440  0.163436  0.163435  0.163433  0.163430  0.163430
 [1331]  0.163425  0.163424  0.163424  0.163417  0.163407  0.163403  0.163392
 [1338]  0.163381  0.163379  0.163374  0.163369  0.163361  0.163360  0.163352
 [1345]  0.163351  0.163346  0.163341  0.163339  0.163333  0.163306  0.163300
 [1352]  0.163299  0.163297  0.163295  0.163289  0.163282  0.163280  0.163273
 [1359]  0.163266  0.163258  0.163256  0.163234  0.163233  0.163224  0.163223
 [1366]  0.163221  0.163213  0.163210  0.163206  0.163178  0.163174  0.163169
 [1373]  0.163163  0.163149  0.163147  0.163142  0.163137  0.163132  0.163130
 [1380]  0.163122  0.163113  0.163111  0.163104  0.163098  0.163085  0.163083
 [1387]  0.163083  0.163082  0.163079  0.163075  0.163074  0.163072  0.163071
 [1394]  0.163068  0.163063  0.163060  0.163055  0.163052  0.163052  0.163039
 [1401]  0.163031  0.163024  0.163016  0.163016  0.163012  0.163011  0.163010
 [1408]  0.163009  0.163006  0.163004  0.162992  0.162981  0.162977  0.162960
 [1415]  0.162940  0.162934  0.162932  0.162932  0.162926  0.162923  0.162916
 [1422]  0.162915  0.162914  0.162911  0.162906  0.162905  0.162903  0.162896
 [1429]  0.162878  0.162877  0.162875  0.162875  0.162870  0.162870  0.162867
 [1436]  0.162863  0.162859  0.162854  0.162850  0.162838  0.162836  0.162835
 [1443]  0.162833  0.162833  0.162829  0.162829  0.162825  0.162823  0.162822
 [1450]  0.162817  0.162810  0.162808  0.162807  0.162799  0.162795  0.162784
 [1457]  0.162775  0.162771  0.162770  0.162766  0.162760  0.162758  0.162756
 [1464]  0.162755  0.162751  0.162750  0.162746  0.162727  0.162720  0.162713
 [1471]  0.162696  0.162686  0.162681  0.162666  0.162658  0.162643  0.162642
 [1478]  0.162642  0.162636  0.162633  0.162624  0.162620  0.162618  0.162603
 [1485]  0.162596  0.162596  0.162594  0.162586  0.162575  0.162564  0.162561
 [1492]  0.162556  0.162556  0.162555  0.162553  0.162550  0.162549  0.162546
 [1499]  0.162544  0.162538  0.162534  0.162531  0.162528  0.162527  0.162525
 [1506]  0.162509  0.162509  0.162506  0.162497  0.162487  0.162486  0.162482
 [1513]  0.162480  0.162465  0.162463  0.162453  0.162451  0.162425  0.162424
 [1520]  0.162420  0.162415  0.162412  0.162411  0.162409  0.162405  0.162400
 [1527]  0.162398  0.162389  0.162381  0.162372  0.162371  0.162352  0.162349
 [1534]  0.162347  0.162330  0.162329  0.162325  0.162322  0.162314  0.162303
 [1541]  0.162301  0.162296  0.162294  0.162290  0.162290  0.162289  0.162289
 [1548]  0.162288  0.162282  0.162281  0.162280  0.162270  0.162269  0.162262
 [1555]  0.162260  0.162234  0.162229  0.162228  0.162227  0.162212  0.162210
 [1562]  0.162196  0.162196  0.162182  0.162164  0.162146  0.162140  0.162139
 [1569]  0.162132  0.162130  0.162119  0.162119  0.162113  0.162105  0.162093
 [1576]  0.162091  0.162086  0.162085  0.162083  0.162081  0.162074  0.162067
 [1583]  0.162062  0.162058  0.162048  0.162046  0.162046  0.162045  0.162044
 [1590]  0.162043  0.162043  0.162037  0.162035  0.162030  0.162017  0.162012
 [1597]  0.162009  0.162007  0.161992  0.161992  0.161989  0.161980  0.161970
 [1604]  0.161968  0.161968  0.161967  0.161950  0.161946  0.161937  0.161937
 [1611]  0.161933  0.161931  0.161931  0.161924  0.161917  0.161915  0.161911
 [1618]  0.161909  0.161909  0.161903  0.161897  0.161894  0.161892  0.161885
 [1625]  0.161879  0.161877  0.161872  0.161872  0.161871  0.161865  0.161863
 [1632]  0.161839  0.161837  0.161834  0.161826  0.161823  0.161812  0.161812
 [1639]  0.161811  0.161810  0.161805  0.161794  0.161792  0.161792  0.161792
 [1646]  0.161791  0.161786  0.161784  0.161781  0.161771  0.161770  0.161766
 [1653]  0.161756  0.161756  0.161754  0.161750  0.161742  0.161734  0.161727
 [1660]  0.161727  0.161723  0.161721  0.161720  0.161720  0.161720  0.161718
 [1667]  0.161717  0.161714  0.161701  0.161700  0.161693  0.161688  0.161686
 [1674]  0.161671  0.161668  0.161655  0.161652  0.161650  0.161650  0.161649
 [1681]  0.161644  0.161643  0.161641  0.161640  0.161636  0.161633  0.161618
 [1688]  0.161614  0.161611  0.161610  0.161607  0.161606  0.161604  0.161600
 [1695]  0.161594  0.161588  0.161574  0.161562  0.161561  0.161559  0.161556
 [1702]  0.161553  0.161549  0.161538  0.161537  0.161529  0.161519  0.161497
 [1709]  0.161496  0.161494  0.161491  0.161483  0.161478  0.161477  0.161475
 [1716]  0.161470  0.161465  0.161460  0.161456  0.161454  0.161450  0.161442
 [1723]  0.161422  0.161422  0.161414  0.161408  0.161405  0.161394  0.161393
 [1730]  0.161390  0.161389  0.161383  0.161383  0.161380  0.161379  0.161376
 [1737]  0.161363  0.161358  0.161358  0.161352  0.161345  0.161341  0.161333
 [1744]  0.161333  0.161326  0.161320  0.161310  0.161310  0.161309  0.161309
 [1751]  0.161300  0.161294  0.161293  0.161292  0.161288  0.161286  0.161286
 [1758]  0.161286  0.161278  0.161273  0.161272  0.161268  0.161253  0.161252
 [1765]  0.161241  0.161223  0.161210  0.161208  0.161201  0.161196  0.161168
 [1772]  0.161167  0.161161  0.161158  0.161157  0.161156  0.161154  0.161145
 [1779]  0.161145  0.161136  0.161134  0.161125  0.161124  0.161113  0.161111
 [1786]  0.161097  0.161094  0.161089  0.161088  0.161083  0.161083  0.161083

In [20]:
#Sort out potential clones
clones<-rels_all[rels_all$KING>0.35,]

In [22]:
#Looks like two potential clone pairs
clones

      a   b   nSites  J9       J8      J7       J6    J5 J4 J3 ⋯
25961 176 177 3984467 0.192783 5.0e-05 0.807166 0e+00 0  0  0  ⋯
26786 192 194 3986482 0.177092 5.3e-05 0.822854 1e-06 0  0  0  ⋯
      X2dsfs
25961 6.355650e-01,3.583657e-02,1.357185e-10,4.053355e-02,2.613623e-01,4.224555e-04,3.476200e-10,4.644084e-04,2.581565e-02
26786 6.400557e-01,3.466675e-02,1.511623e-09,3.511383e-02,2.635376e-01,4.343429e-04,1.845300e-09,4.501945e-04,2.574157e-02
      R0 R1       KING     X2dsfs_loglike X2dsfsf_niter IndA    IndB    BayA
25961 0  3.383025 0.435617 -4363988       11            ACR_416 ACR_419 0
26786 0  3.729388 0.440890 -4273474       10            ACR_502 ACR_505 0
      BayB
25961 0
26786 0

In [23]:
#Figure out which individuals are clones
clones$IndA
clones$IndB

[1] "ACR_416" "ACR_502"

[1] "ACR_419" "ACR_505"

In [26]:
metadat<-read.csv('/home/jbos/Moz_reads/Acropora_moz_metadat_certainty.csv')

In [27]:
leading_zeros<-function(num){
    if (nchar(as.character(num))<2){
        return(paste0('00',num))
        } else {
        if (nchar(as.character(num))<3){
            return(paste0('0',num))
            } else {
       return(as.character(num))
            }
        }
    }

In [28]:
#Add leading zero where necessary
metadat$Numero_do_tubo<-sapply(metadat$Numero_do_tubo,leading_zeros)

In [29]:
metadat$IND<-paste("ACR_",metadat$Numero_do_tubo,sep="")

In [31]:
clones1<-metadat[metadat$IND %in% c('ACR_416','ACR_419'),]
clones2<-metadat[metadat$IND %in% c('ACR_502','ACR_505'),]

In [32]:
clones1

    Numero_do_tubo Latitude  Longitude Profundidade_metros Dia Mes Ano  Bleach
162 416            -12.96453 40.54864  5.4                 13  5   2024 N
167 419            -12.96453 40.54864  4.2                 13  5   2024 N
    SppIDCertainty Loc Spp IND
162 C              W   A   ACR_416
167 C              W   A   ACR_419

In [38]:
clones2
p1<-c(clones2$Longitude[1],clones2$Latitude[1])
p2<-c(clones2$Longitude[2],clones2$Latitude[2])

    Numero_do_tubo Latitude  Longitude Profundidade_metros Dia Mes Ano  Bleach
181 502            -12.96111 40.55250  7.8                 21  5   2024 N
202 505            -12.96556 40.54583  4.2                 23  5   2024 N
    SppIDCertainty Loc Spp IND
181 C              W   A   ACR_502
202 C              W   A   ACR_505

In [39]:
distHaversine(p1,p2)

[1] 876.3193

In [25]:
#All at Wimbe, incidentally
'ACR_416' %in% grp1
'ACR_502' %in% grp1
'ACR_419' %in% grp1
'ACR_505' %in% grp1

[1] FALSE

[1] FALSE

[1] FALSE

[1] FALSE

In [46]:
table(rels_all$KING>0.177)

FALSE  TRUE
27537   193

In [47]:
mayberels<-rels_all[rels_all$KING>0.177,]

In [48]:
mayberels[order(-mayberels$KING),c('IndA','IndB','KING','X2dsfs_loglike')]

      IndA    IndB    KING     X2dsfs_loglike
26786 ACR_502 ACR_505 0.440890 -4273474
25961 ACR_416 ACR_419 0.435617 -4363988
751   ACR_019 ACR_702 0.238824 -5365158
4093  ACR_481 ACR_541 0.238658 -5607580
4324  ACR_486 ACR_598 0.227789 -5587177
11812 ACR_707 ACR_729 0.226161 -5581459
15650 ACR_304 ACR_314 0.221046 -2805856
23055 ACR_568 ACR_558 0.216856 -5605434
6823  ACR_535 ACR_541 0.212239 -5659277
3462  ACR_433 ACR_707 0.211282 -5661131
21792 ACR_447 ACR_437 0.209890 -1280632
26280 ACR_435 ACR_558 0.208177 -5748770
17464 ACR_316 ACR_348 0.207401 -5104487
3475  ACR_433 ACR_729 0.203856 -5660132
6237  ACR_528 ACR_715 0.198747 -5685686
274   ACR_011 ACR_563 0.194990 -5603387
18120 ACR_320 ACR_558 0.193659 -5753461
7025  ACR_536 ACR_537 0.192583 -5755117
26333 ACR_436 ACR_558 0.192014 -5742869
21383 ACR_348 ACR_558 0.191867 -5110236
15776 ACR_304 ACR_558 0.191629 -2971145
15682 ACR_304 ACR_348 0.191571 -2760172
17271 ACR_314 ACR_558 0.191509 -5285841
7237  ACR_537 ACR_574 0.190703 -4941478
3438  ACR_433 ACR_537 0.190577 -5752908
7238  ACR_537 ACR_576 0.190056 -5752033
27557 ACR_558 ACR_713 0.189347 -5769478
5373  ACR_517 ACR_537 0.189222 -5725425
27435 ACR_551 ACR_558 0.189065 -5753740
7259  ACR_537 ACR_717 0.188384 -5758267
⋮     ⋮       ⋮       ⋮        ⋮
19196 ACR_328 ACR_558 0.178637 -5801386
25226 ACR_113 ACR_558 0.178477 -5347720
7050  ACR_536 ACR_709 0.178456 -5745909
27116 ACR_518 ACR_558 0.178331 -5543309
3463  ACR_433 ACR_709 0.178307 -5738717
24308 ACR_625 ACR_558 0.178266 -5778929
249   ACR_011 ACR_433 0.178150 -5708547
7264  ACR_537 ACR_729 0.178069 -5748994
15724 ACR_304 ACR_113 0.177858 -2857654
7030  ACR_536 ACR_557 0.177837 -5679062
27547 ACR_558 ACR_577 0.177823 -5789223
7243  ACR_537 ACR_598 0.177771 -5772781
21308 ACR_348 ACR_579 0.177707 -4525572
19836 ACR_335 ACR_558 0.177608 -5801603
7235  ACR_537 ACR_566 0.177603 -5753552
4969  ACR_511 ACR_702 0.177601 -5621125
7263  ACR_537 ACR_726 0.177600 -5767917
3425  ACR_433 ACR_487 0.177557 -5754156
3437  ACR_433 ACR_536 0.177546 -5763739
15930 ACR_305 ACR_558 0.177505 -5797400
27458 ACR_552 ACR_558 0.177485 -5733729
16833 ACR_311 ACR_558 0.177483 -5807134
21270 ACR_347 ACR_558 0.177352 -5794959
5372  ACR_517 ACR_536 0.177333 -5732494
27276 ACR_531 ACR_558 0.177294 -5772925
11274 ACR_704 ACR_726 0.177252 -5731385
7061  ACR_536 ACR_726 0.177089 -5747398
17700 ACR_317 ACR_558 0.177036 -5794859
15671 ACR_304 ACR_337 0.177014 -2558388
3433  ACR_433 ACR_528 0.177003 -5747397

In [49]:
which(colnames(rels_all)=='theta')

[1] 16

In [50]:
rels_all[order(-rels_all$theta),16]

    [1] 0.411440 0.403595 0.186726 0.185896 0.161213 0.151387 0.146369 0.145220
    [9] 0.142596 0.118941 0.115048 0.112129 0.110983 0.104490 0.103316 0.103243
   [17] 0.094674 0.089631 0.088784 0.083895 0.082448 0.081139 0.080835 0.078658
   [25] 0.078429 0.077988 0.077146 0.076594 0.076478 0.076341 0.075925 0.075502
   [33] 0.073505 0.073313 0.073267 0.072982 0.072849 0.072354 0.072343 0.072000
   [41] 0.071964 0.071300 0.071203 0.071103 0.071085 0.070914 0.070881 0.070500
   [49] 0.070455 0.070094 0.070045 0.069968 0.069945 0.069932 0.069791 0.069789
   [57] 0.069616 0.069488 0.069465 0.069436 0.069431 0.069410 0.069356 0.069276
   [65] 0.069262 0.069256 0.069250 0.069196 0.069129 0.069097 0.069081 0.068940
   [73] 0.068909 0.068885 0.068869 0.068781 0.068749 0.068609 0.068557 0.068551
   [81] 0.068463 0.068462 0.068449 0.068393 0.068362 0.068348 0.068223 0.068107
   [89] 0.068093 0.068085 0.067968 0.067817 0.067746 0.067708 0.067688 0.067601
   [97] 0.067568 0.067493 0.067350 0.067314 0.067257 0.067233 0.067218 0.067211
  [105] 0.067168 0.067081 0.067037 0.066977 0.066965 0.066956 0.066918 0.066918
  [113] 0.066842 0.066832 0.066770 0.066764 0.066760 0.066758 0.066749 0.066740
  [121] 0.066730 0.066711 0.066707 0.066679 0.066661 0.066658 0.066650 0.066612
  [129] 0.066595 0.066583 0.066569 0.066555 0.066461 0.066438 0.066423 0.066422
  [137] 0.066306 0.066251 0.066187 0.066174 0.066167 0.066109 0.066091 0.066071
  [145] 0.066067 0.066032 0.066003 0.065994 0.065974 0.065970 0.065941 0.065915
  [153] 0.065889 0.065843 0.065841 0.065840 0.065755 0.065745 0.065743 0.065714
  [161] 0.065676 0.065667 0.065641 0.065621 0.065608 0.065524 0.065476 0.065405
  [169] 0.065385 0.065339 0.065331 0.065281 0.065273 0.065272 0.065270 0.065264
  [177] 0.065229 0.065220 0.065215 0.065208 0.065164 0.065154 0.065123 0.065122
  [185] 0.064980 0.064960 0.064948 0.064889 0.064886 0.064865 0.064809 0.064781
  [193] 0.064776 0.064762 0.064745 0.064744 0.064708 0.064693 0.064681 0.064647
  [201] 0.064640 0.064606 0.064602 0.064599 0.064595 0.064559 0.064540 0.064529
  [209] 0.064472 0.064458 0.064425 0.064398 0.064394 0.064359 0.064354 0.064338
  [217] 0.064304 0.064284 0.064236 0.064228 0.064227 0.064220 0.064202 0.064179
  [225] 0.064179 0.064156 0.064142 0.064136 0.064128 0.064120 0.064119 0.064064
  [233] 0.064036 0.064017 0.064016 0.064006 0.063987 0.063946 0.063891 0.063863
  [241] 0.063849 0.063832 0.063829 0.063825 0.063819 0.063797 0.063757 0.063754
  [249] 0.063750 0.063745 0.063725 0.063724 0.063715 0.063700 0.063698 0.063631
  [257] 0.063601 0.063595 0.063573 0.063564 0.063540 0.063532 0.063511 0.063499
  [265] 0.063490 0.063489 0.063488 0.063465 0.063440 0.063406 0.063389 0.063373
  [273] 0.063364 0.063337 0.063313 0.063287 0.063284 0.063278 0.063275 0.063262
  [281] 0.063251 0.063236 0.063208 0.063165 0.063148 0.063142 0.063140 0.063115
  [289] 0.063105 0.063098 0.063093 0.063091 0.063056 0.063052 0.063014 0.063005
  [297] 0.062992 0.062988 0.062980 0.062978 0.062968 0.062961 0.062957 0.062939
  [305] 0.062936 0.062893 0.062888 0.062874 0.062869 0.062868 0.062850 0.062796
  [313] 0.062792 0.062786 0.062783 0.062773 0.062766 0.062764 0.062762 0.062755
  [321] 0.062718 0.062718 0.062717 0.062686 0.062684 0.062678 0.062672 0.062651
  [329] 0.062650 0.062645 0.062640 0.062629 0.062623 0.062609 0.062585 0.062559
  [337] 0.062555 0.062540 0.062537 0.062483 0.062457 0.062434 0.062407 0.062400
  [345] 0.062397 0.062392 0.062387 0.062360 0.062353 0.062346 0.062338 0.062336
  [353] 0.062319 0.062315 0.062293 0.062287 0.062253 0.062251 0.062232 0.062232
  [361] 0.062223 0.062190 0.062188 0.062165 0.062154 0.062139 0.062132 0.062119
  [369] 0.062119 0.062092 0.062084 0.062054 0.062048 0.062047 0.062044 0.062035
  [377] 0.062035 0.061998 0.061986 0.061972 0.061970 0.061961 0.061961 0.061936
  [385] 0.061915 0.061914 0.061906 0.061898 0.061876 0.061844 0.061824 0.061801
  [393] 0.061788 0.061786 0.061781 0.061770 0.061758 0.061754 0.061754 0.061744
  [401] 0.061741 0.061739 0.061728 0.061724 0.061719 0.061702 0.061688 0.061660
  [409] 0.061644 0.061642 0.061640 0.061633 0.061628 0.061626 0.061616 0.061613
  [417] 0.061611 0.061601 0.061567 0.061564 0.061553 0.061548 0.061538 0.061533
  [425] 0.061526 0.061506 0.061502 0.061469 0.061451 0.061430 0.061409 0.061405
  [433] 0.061386 0.061372 0.061361 0.061357 0.061325 0.061321 0.061317 0.061297
  [441] 0.061281 0.061278 0.061275 0.061270 0.061260 0.061256 0.061249 0.061239
  [449] 0.061234 0.061230 0.061218 0.061218 0.061206 0.061206 0.061199 0.061198
  [457] 0.061194 0.061185 0.061169 0.061169 0.061159 0.061153 0.061137 0.061135
  [465] 0.061112 0.061111 0.061100 0.061092 0.061091 0.061082 0.061078 0.061028
  [473] 0.061012 0.061007 0.060998 0.060981 0.060980 0.060976 0.060973 0.060961
  [481] 0.060960 0.060953 0.060949 0.060931 0.060929 0.060876 0.060875 0.060865
  [489] 0.060854 0.060851 0.060847 0.060838 0.060831 0.060822 0.060819 0.060810
  [497] 0.060777 0.060768 0.060745 0.060738 0.060729 0.060701 0.060693 0.060666
  [505] 0.060658 0.060632 0.060631 0.060629 0.060592 0.060587 0.060578 0.060575
  [513] 0.060574 0.060566 0.060555 0.060553 0.060552 0.060544 0.060528 0.060511
  [521] 0.060497 0.060496 0.060480 0.060478 0.060460 0.060458 0.060449 0.060449
  [529] 0.060444 0.060423 0.060361 0.060360 0.060348 0.060339 0.060299 0.060298
  [537] 0.060279 0.060278 0.060276 0.060268 0.060242 0.060238 0.060224 0.060215
  [545] 0.060214 0.060211 0.060205 0.060193 0.060187 0.060179 0.060179 0.060177
  [553] 0.060176 0.060173 0.060172 0.060169 0.060154 0.060133 0.060131 0.060117
  [561] 0.060108 0.060107 0.060103 0.060092 0.060088 0.060085 0.060069 0.060069
  [569] 0.060066 0.060065 0.060049 0.060033 0.060032 0.060028 0.060027 0.060022
  [577] 0.060007 0.059979 0.059978 0.059968 0.059965 0.059963 0.059957 0.059957
  [585] 0.059953 0.059949 0.059946 0.059920 0.059896 0.059890 0.059887 0.059878
  [593] 0.059877 0.059875 0.059868 0.059861 0.059859 0.059851 0.059844 0.059841
  [601] 0.059832 0.059826 0.059806 0.059787 0.059767 0.059760 0.059750 0.059733
  [609] 0.059728 0.059724 0.059723 0.059691 0.059684 0.059681 0.059666 0.059654
  [617] 0.059637 0.059633 0.059623 0.059615 0.059610 0.059606 0.059601 0.059595
  [625] 0.059595 0.059589 0.059585 0.059564 0.059552 0.059544 0.059542 0.059517
  [633] 0.059514 0.059513 0.059511 0.059510 0.059500 0.059500 0.059494 0.059491
  [641] 0.059491 0.059478 0.059469 0.059468 0.059454 0.059453 0.059445 0.059441
  [649] 0.059422 0.059422 0.059416 0.059399 0.059397 0.059396 0.059396 0.059392
  [657] 0.059378 0.059373 0.059372 0.059341 0.059330 0.059317 0.059316 0.059299
  [665] 0.059276 0.059276 0.059270 0.059266 0.059262 0.059244 0.059235 0.059227
  [673] 0.059225 0.059224 0.059220 0.059214 0.059204 0.059203 0.059192 0.059180
  [681] 0.059171 0.059170 0.059168 0.059168 0.059166 0.059158 0.059157 0.059151
  [689] 0.059127 0.059126 0.059123 0.059123 0.059122 0.059109 0.059102 0.059092
  [697] 0.059092 0.059081 0.059078 0.059054 0.059049 0.059046 0.059016 0.058994
  [705] 0.058993 0.058986 0.058972 0.058964 0.058957 0.058902 0.058885 0.058884
  [713] 0.058875 0.058865 0.058858 0.058846 0.058833 0.058829 0.058829 0.058817
  [721] 0.058815 0.058815 0.058812 0.058807 0.058787 0.058787 0.058775 0.058769
  [729] 0.058762 0.058758 0.058757 0.058748 0.058725 0.058725 0.058714 0.058697
  [737] 0.058668 0.058656 0.058643 0.058636 0.058625 0.058623 0.058619 0.058615
  [745] 0.058599 0.058599 0.058577 0.058570 0.058567 0.058562 0.058551 0.058545
  [753] 0.058545 0.058539 0.058538 0.058532 0.058530 0.058519 0.058495 0.058492
  [761] 0.058491 0.058490 0.058483 0.058477 0.058463 0.058456 0.058443 0.058443
  [769] 0.058432 0.058429 0.058420 0.058420 0.058418 0.058408 0.058400 0.058399
  [777] 0.058397 0.058384 0.058363 0.058361 0.058361 0.058345 0.058333 0.058319
  [785] 0.058300 0.058292 0.058277 0.058259 0.058256 0.058243 0.058240 0.058238
  [793] 0.058237 0.058235 0.058228 0.058207 0.058194 0.058189 0.058183 0.058179
  [801] 0.058154 0.058151 0.058144 0.058143 0.058138 0.058134 0.058123 0.058099
  [809] 0.058090 0.058077 0.058074 0.058074 0.058072 0.058070 0.058069 0.058064
  [817] 0.058063 0.058061 0.058060 0.058043 0.058042 0.058041 0.058037 0.058036
  [825] 0.058034 0.058017 0.058013 0.058010 0.057993 0.057993 0.057987 0.057979
  [833] 0.057978 0.057970 0.057968 0.057957 0.057950 0.057949 0.057928 0.057921
  [841] 0.057908 0.057908 0.057900 0.057895 0.057893 0.057878 0.057875 0.057872
  [849] 0.057866 0.057855 0.057845 0.057836 0.057826 0.057824 0.057819 0.057815
  [857] 0.057813 0.057808 0.057797 0.057791 0.057777 0.057763 0.057756 0.057751
  [865] 0.057747 0.057746 0.057739 0.057739 0.057727 0.057723 0.057722 0.057722
  [873] 0.057692 0.057684 0.057681 0.057672 0.057664 0.057636 0.057636 0.057628
  [881] 0.057623 0.057614 0.057612 0.057609 0.057598 0.057577 0.057554 0.057546
  [889] 0.057541 0.057537 0.057528 0.057517 0.057499 0.057494 0.057492 0.057487
  [897] 0.057485 0.057468 0.057463 0.057463 0.057463 0.057448 0.057445 0.057432
  [905] 0.057432 0.057430 0.057426 0.057418 0.057415 0.057411 0.057407 0.057401
  [913] 0.057397 0.057396 0.057390 0.057388 0.057381 0.057373 0.057372 0.057364
  [921] 0.057346 0.057325 0.057320 0.057312 0.057307 0.057305 0.057304 0.057303
  [929] 0.057301 0.057291 0.057289 0.057284 0.057276 0.057263 0.057261 0.057252
  [937] 0.057252 0.057245 0.057235 0.057233 0.057233 0.057225 0.057217 0.057198
  [945] 0.057190 0.057178 0.057174 0.057170 0.057167 0.057162 0.057159 0.057156
  [953] 0.057128 0.057127 0.057124 0.057120 0.057118 0.057117 0.057115 0.057114
  [961] 0.057097 0.057088 0.057087 0.057084 0.057075 0.057072 0.057066 0.057062
  [969] 0.057058 0.057057 0.057045 0.057039 0.057031 0.056998 0.056998 0.056975
  [977] 0.056971 0.056970 0.056964 0.056959 0.056947 0.056946 0.056927 0.056919
  [985] 0.056911 0.056909 0.056903 0.056903 0.056898 0.056894 0.056876 0.056834
  [993] 0.056818 0.056804 0.056798 0.056793 0.056777 0.056777 0.056769 0.056765
 [1001] 0.056758 0.056754 0.056726 0.056724 0.056720 0.056714 0.056706 0.056703
 [1009] 0.056696 0.056692 0.056688 0.056667 0.056663 0.056659 0.056652 0.056643
 [1017] 0.056630 0.056629 0.056626 0.056607 0.056598 0.056595 0.056595 0.056580
 [1025] 0.056566 0.056564 0.056563 0.056549 0.056548 0.056511 0.056510 0.056497
 [1033] 0.056479 0.056478 0.056475 0.056467 0.056461 0.056452 0.056447 0.056445
 [1041] 0.056435 0.056425 0.056424 0.056421 0.056413 0.056395 0.056384 0.056372
 [1049] 0.056369 0.056361 0.056358 0.056351 0.056333 0.056304 0.056303 0.056301
 [1057] 0.056294 0.056292 0.056285 0.056285 0.056279 0.056272 0.056271 0.056262
 [1065] 0.056255 0.056252 0.056251 0.056251 0.056243 0.056239 0.056236 0.056235
 [1073] 0.056235 0.056230 0.056221 0.056216 0.056210 0.056202 0.056199 0.056197
 [1081] 0.056195 0.056194 0.056190 0.056189 0.056188 0.056187 0.056178 0.056172
 [1089] 0.056169 0.056155 0.056152 0.056150 0.056150 0.056142 0.056133 0.056132
 [1097] 0.056129 0.056119 0.056115 0.056114 0.056111 0.056093 0.056079 0.056064
 [1105] 0.056051 0.056051 0.056026 0.056020 0.056017 0.056014 0.056012 0.055997
 [1113] 0.055995 0.055994 0.055993 0.055987 0.055986 0.055976 0.055968 0.055964
 [1121] 0.055960 0.055959 0.055949 0.055948 0.055940 0.055940 0.055929 0.055913
 [1129] 0.055908 0.055907 0.055904 0.055900 0.055895 0.055892 0.055886 0.055879
 [1137] 0.055875 0.055869 0.055857 0.055846 0.055839 0.055835 0.055834 0.055834
 [1145] 0.055833 0.055832 0.055831 0.055828 0.055828 0.055823 0.055822 0.055820
 [1153] 0.055817 0.055815 0.055806 0.055798 0.055797 0.055790 0.055789 0.055787
 [1161] 0.055776 0.055766 0.055759 0.055756 0.055739 0.055739 0.055737 0.055737
 [1169] 0.055736 0.055735 0.055732 0.055725 0.055722 0.055720 0.055715 0.055709
 [1177] 0.055707 0.055700 0.055698 0.055692 0.055670 0.055652 0.055645 0.055620
 [1185] 0.055616 0.055609 0.055601 0.055595 0.055575 0.055551 0.055548 0.055545
 [1193] 0.055544 0.055543 0.055538 0.055536 0.055533 0.055522 0.055517 0.055502
 [1201] 0.055500 0.055500 0.055491 0.055484 0.055479 0.055473 0.055473 0.055461
 [1209] 0.055454 0.055453 0.055436 0.055433 0.055430 0.055417 0.055417 0.055412
 [1217] 0.055408 0.055398 0.055397 0.055389 0.055386 0.055385 0.055384 0.055382
 [1225] 0.055381 0.055373 0.055373 0.055371 0.055367 0.055367 0.055360 0.055357
 [1233] 0.055353 0.055325 0.055317 0.055307 0.055303 0.055301 0.055299 0.055296
 [1241] 0.055277 0.055277 0.055268 0.055267 0.055260 0.055259 0.055246 0.055236
 [1249] 0.055236 0.055236 0.055235 0.055215 0.055212 0.055211 0.055198 0.055195
 [1257] 0.055193 0.055192 0.055189 0.055183 0.055169 0.055155 0.055146 0.055138
 [1265] 0.055128 0.055114 0.055108 0.055105 0.055100 0.055100 0.055096 0.055072
 [1273] 0.055071 0.055067 0.055066 0.055057 0.055057 0.055057 0.055055 0.055046
 [1281] 0.055038 0.055036 0.055030 0.055022 0.055019 0.055019 0.055010 0.055000
 [1289] 0.054991 0.054988 0.054982 0.054974 0.054958 0.054946 0.054938 0.054937
 [1297] 0.054934 0.054915 0.054911 0.054910 0.054903 0.054890 0.054887 0.054883
 [1305] 0.054880 0.054874 0.054869 0.054863 0.054863 0.054851 0.054843 0.054832
 [1313] 0.054813 0.054809 0.054807 0.054803 0.054800 0.054790 0.054789 0.054761
 [1321] 0.054757 0.054742 0.054733 0.054733 0.054730 0.054717 0.054715 0.054714
 [1329] 0.054706 0.054706 0.054695 0.054691 0.054690 0.054690 0.054687 0.054683
 [1337] 0.054676 0.054668 0.054664 0.054650 0.054645 0.054643 0.054642 0.054619
 [1345] 0.054618 0.054617 0.054609 0.054609 0.054601 0.054600 0.054599 0.054594
 [1353] 0.054574 0.054573 0.054569 0.054565 0.054561 0.054549 0.054548 0.054543
 [1361] 0.054535 0.054525 0.054520 0.054482 0.054473 0.054465 0.054461 0.054455
 [1369] 0.054450 0.054449 0.054441 0.054440 0.054427 0.054423 0.054421 0.054421
 [1377] 0.054421 0.054416 0.054415 0.054415 0.054413 0.054402 0.054400 0.054397
 [1385] 0.054385 0.054384 0.054379 0.054364 0.054341 0.054337 0.054334 0.054330
 [1393] 0.054328 0.054314 0.054312 0.054311 0.054307 0.054294 0.054293 0.054291
 [1401] 0.054291 0.054284 0.054280 0.054277 0.054272 0.054270 0.054269 0.054265
 [1409] 0.054257 0.054257 0.054254 0.054249 0.054247 0.054238 0.054236 0.054235
 [1417] 0.054233 0.054232 0.054219 0.054213 0.054212 0.054209 0.054207 0.054203
 [1425] 0.054201 0.054200 0.054193 0.054190 0.054187 0.054171 0.054166 0.054156
 [1433] 0.054135 0.054131 0.054127 0.054127 0.054126 0.054121 0.054118 0.054111
 [1441] 0.054097 0.054090 0.054088 0.054088 0.054077 0.054075 0.054059 0.054058
 [1449] 0.054056 0.054051 0.054050 0.054046 0.054041 0.054034 0.054031 0.054031
 [1457] 0.054027 0.054007 0.054006 0.053984 0.053982 0.053981 0.053971 0.053971
 [1465] 0.053970 0.053969 0.053966 0.053961 0.053961 0.053945 0.053944 0.053936
 [1473] 0.053933 0.053922 0.053894 0.053894 0.053883 0.053881 0.053881 0.053877
 [1481] 0.053870 0.053861 0.053861 0.053847 0.053845 0.053820 0.053812 0.053811
 [1489] 0.053809 0.053808 0.053805 0.053803 0.053801 0.053795 0.053794 0.053786
 [1497] 0.053786 0.053785 0.053782 0.053780 0.053780 0.053772 0.053768 0.053764
 [1505] 0.053742 0.053741 0.053729 0.053716 0.053701 0.053698 0.053697 0.053678
 [1513] 0.053672 0.053672 0.053664 0.053661 0.053657 0.053647 0.053639 0.053637
 [1521] 0.053636 0.053624 0.053614 0.053611 0.053604 0.053599 0.053595 0.053590
 [1529] 0.053583 0.053579 0.053577 0.053567 0.053564 0.053559 0.053548 0.053544
 [1537] 0.053538 0.053537 0.053530 0.053518 0.053509 0.053507 0.053475 0.053473
 [1545] 0.053472 0.053460 0.053451 0.053449 0.053439 0.053432 0.053431 0.053429
 [1553] 0.053422 0.053417 0.053414 0.053412 0.053411 0.053408 0.053402 0.053396
 [1561] 0.053392 0.053382 0.053381 0.053377 0.053374 0.053368 0.053366 0.053365
 [1569] 0.053360 0.053357 0.053348 0.053328 0.053326 0.053325 0.053324 0.053323
 [1577] 0.053315 0.053309 0.053304 0.053302 0.053299 0.053299 0.053298 0.053290
 [1585] 0.053289 0.053288 0.053281 0.053281 0.053279 0.053278 0.053269 0.053268
 [1593] 0.053268 0.053256 0.053249 0.053240 0.053231 0.053228 0.053217 0.053215
 [1601] 0.053209 0.053209 0.053206 0.053203 0.053196 0.053180 0.053176 0.053176
 [1609] 0.053164 0.053151 0.053130 0.053129 0.053127 0.053121 0.053117 0.053115
 [1617] 0.053108 0.053088 0.053079 0.053072 0.053058 0.053057 0.053052 0.053043
 [1625] 0.053043 0.053041 0.053041 0.053034 0.053033 0.053017 0.053017 0.053015
 [1633] 0.053015 0.052997 0.052991 0.052987 0.052974 0.052971 0.052970 0.052961
 [1641] 0.052959 0.052937 0.052926 0.052921 0.052913 0.052910 0.052905 0.052904
 [1649] 0.052904 0.052897 0.052896 0.052890 0.052889 0.052884 0.052882 0.052875
 [1657] 0.052855 0.052848 0.052848 0.052848 0.052843 0.052820 0.052820 0.052798
 [1665] 0.052792 0.052787 0.052781 0.052780 0.052777 0.052777 0.052774 0.052771
 [1673] 0.052767 0.052764 0.052747 0.052738 0.052734 0.052723 0.052719 0.052716
 [1681] 0.052711 0.052691 0.052689 0.052686 0.052677 0.052670 0.052666 0.052665
 [1689] 0.052652 0.052650 0.052638 0.052629 0.052628 0.052623 0.052619 0.052617
 [1697] 0.052598 0.052577 0.052574 0.052573 0.052570 0.052559 0.052544 0.052528
 [1705] 0.052527 0.052523 0.052518 0.052509 0.052501 0.052489 0.052481 0.052468
 [1713] 0.052465 0.052464 0.052462 0.052442 0.052442 0.052439 0.052434 0.052424
 [1721] 0.052419 0.052410 0.052402 0.052397 0.052386 0.052381 0.052369 0.052363
 [1729] 0.052359 0.052352 0.052335 0.052329 0.052321 0.052307 0.052270 0.052265
 [1737] 0.052262 0.052261 0.052253 0.052247 0.052247 0.052243 0.052239 0.052237
 [1745] 0.052235 0.052232 0.052229 0.052226 0.052220 0.052216 0.052200 0.052187
 [1753] 0.052183 0.052180 0.052172 0.052159 0.052143 0.052134 0.052114 0.052093
 [1761] 0.052089 0.052089 0.052086 0.052082 0.052075 0.052071 0.052064 0.052056
 [1769] 0.052033 0.052031 0.052019 0.052017 0.052016 0.051974 0.051966 0.051963
 [1777] 0.051946 0.051943 0.051943 0.051927 0.051924 0.051898 0.051893 0.051885
 [1785] 0.051882 0.051876 0.051872 0.051853 0.051851 0.051848 0.051847 0.051844
 [1793] 0.051840 0.051839 0.051833 0.051833 0.051818 0.051817 0.051812 0.051812
 [1801] 0.051805 0.051793 0.051787 0.051786 0.051784 0.051767 0.051763 0.051758
 [1809] 0.051755 0.051733 0.051726 0.051723 0.051717 0.051707 0.051705 0.051696
 [1817] 0.051691 0.051683 0.051683 0.051676 0.051664 0.051661 0.051644 0.051633
 [1825] 0.051630 0.051626 0.051626 0.051625 0.051620 0.051618 0.051605 0.051599
 [1833] 0.051595 0.051592 0.051590 0.051588 0.051583 0.051582 0.051580 0.051576
 [1841] 0.051576 0.051571 0.051560 0.051548 0.051548 0.051544 0.051536 0.051536
 [1849] 0.051531 0.051526 0.051526 0.051522 0.051520 0.051519 0.051517 0.051504
 [1857] 0.051503 0.051488 0.051488 0.051485 0.051479 0.051461 0.051454 0.051442
 [1865] 0.051440 0.051422 0.051420 0.051410 0.051404 0.051400 0.051394 0.051392
 [1873] 0.051389 0.051388 0.051380 0.051376 0.051369 0.051363 0.051356 0.051355
 [1881] 0.051354 0.051350 0.051349 0.051343 0.051337 0.051331 0.051323 0.051309
 [1889] 0.051301 0.051296 0.051292 0.051278 0.051271 0.051267 0.051259 0.051255
 [1897] 0.051248 0.051247 0.051244 0.051240 0.051239 0.051222 0.051219 0.051216
 [1905] 0.051191 0.051188 0.051182 0.051177 0.051175 0.051173 0.051172 0.051169
 [1913] 0.051167 0.051157 0.051155 0.051153 0.051150 0.051140 0.051131 0.051122
 [1921] 0.051122 0.051120 0.051118 0.051113 0.051112 0.051104 0.051104 0.051098
 [1929] 0.051089 0.051074 0.051071 0.051069 0.051059 0.051052 0.051046 0.051045
 [1937] 0.051044 0.051041 0.051028 0.051022 0.051017 0.050998 0.050973 0.050953
 [1945] 0.050946 0.050944 0.050940 0.050933 0.050925 0.050914 0.050911 0.050907
 [1953] 0.050889 0.050885 0.050877 0.050862 0.050849 0.050824 0.050802 0.050800
 [1961] 0.050789 0.050780 0.050779 0.050766 0.050756 0.050743 0.050741 0.050732
 [1969] 0.050732 0.050724 0.050714 0.050706 0.050700 0.050685 0.050679 0.050676
 [1977] 0.050675 0.050666 0.050653 0.050652 0.050622 0.050619 0.050617 0.050607
 [1985] 0.050600 0.050594 0.050589 0.050583 0.050550 0.050549 0.050546 0.050542
 [1993] 0.050536 0.050532 0.050527 0.050513 0.050503 0.050500 0.050496 0.050495

In [51]:
median(rels_all$theta)
median(within_bay$theta)

[1] 0.0126005

[1] 0.054613

In [54]:
mayberels<-rels_all[rels_all$theta>0.25,]

In [55]:
mayberels[order(-mayberels$theta),c('IndA','IndB','theta')]

      IndA    IndB    theta
26786 ACR_502 ACR_505 0.411440
25961 ACR_416 ACR_419 0.403595

In [66]:
bamlist<-function(ind){
    a<-paste0('/scratch/jbos/Moz_aligned_mil/amillepora_bamfiles/',ind)
    b<-paste0(a,'.sorted.bam')
    return(b)
    }

In [62]:
which(indlist=='ACR_505')
which(indlist=='ACR_419')

[1] 195

[1] 178

In [64]:
indlist_noclones<-indlist[-c(195,178)]
length(indlist_noclones)

[1] 234

In [67]:
a<-indlist_noclones
a<-bamlist(a)
write.table(a,'/home/jbos/Moz_reads/bam_names_grp137_noclones.txt',row.names=FALSE,col.names=FALSE,quote=FALSE)

In [68]:
bamlist7<-read.table('/home/jbos/Moz_reads/bam_names_grp7.txt')

In [69]:
indlist7<-apply(bamlist7,FUN=bamnames,MARGIN=1)

In [70]:
which(indlist7=='ACR_505')
which(indlist7=='ACR_419')

[1] 36

[1] 19

In [71]:
indlist7_noclones<-indlist7[-c(19,36)]

In [72]:
a<-indlist7_noclones
a<-bamlist(a)
write.table(a,'/home/jbos/Moz_reads/bam_names_grp7_noclones.txt',row.names=FALSE,col.names=FALSE,quote=FALSE)

In [74]:
bamlist37<-read.table('/home/jbos/Moz_reads/bam_names_grp37.txt')

In [75]:
indlist37<-apply(bamlist37,FUN=bamnames,MARGIN=1)

In [76]:
which(indlist37=='ACR_505')
which(indlist37=='ACR_419')

[1] 122

[1] 105

In [77]:
indlist37_noclones<-indlist37[-c(105,122)]

In [78]:
a<-indlist37_noclones
a<-bamlist(a)
write.table(a,'/home/jbos/Moz_reads/bam_names_grp37_noclones.txt',row.names=FALSE,col.names=FALSE,quote=FALSE)